els-ASAP auto commit file/tag gnutls-2.12.23-21.el6.src.rpm

diff --git a/src/tests/userid/userid b/src/tests/userid/userid
--- a/src/tests/userid/userid
+++ b/src/tests/userid/userid
@@ -1,28 +1,36 @@
 #!/bin/sh
 
-# Copyright (C) 2006, 2008 Free Software Foundation
+# Copyright (C) 2006, 2008, 2010 Free Software Foundation, Inc.
 #
 # Author: Simon Josefsson
 #
-# This file is part of GNUTLS.
+# This file is part of GnuTLS.
 #
-# GNUTLS is free software; you can redistribute it and/or modify it
+# GnuTLS is free software; you can redistribute it and/or modify it
 # under the terms of the GNU General Public License as published by the
 # Free Software Foundation; either version 3 of the License, or (at
 # your option) any later version.
 #
-# GNUTLS is distributed in the hope that it will be useful, but
+# GnuTLS is distributed in the hope that it will be useful, but
 # WITHOUT ANY WARRANTY; without even the implied warranty of
 # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 # General Public License for more details.
 #
 # You should have received a copy of the GNU General Public License
-# along with GNUTLS; if not, write to the Free Software Foundation,
+# along with GnuTLS; if not, write to the Free Software Foundation,
 # Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
-
-set -e
 
 srcdir=${srcdir:-.}
 CERTTOOL=${CERTTOOL:-../../src/certtool$EXEEXT}
 
-exec $CERTTOOL --certificate-info --infile $srcdir/userid.pem
+$CERTTOOL --certificate-info --infile $srcdir/userid.pem >out 2>&1
+RET=$?
+if [ $RET !=  0 ];then
+	echo "Error in userid:"
+	cat out
+	exit 1
+fi
+
+rm -f out
+
+exit 0
